name: thai7
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  json_annotation: ^4.6.0
  get_storage: ^2.0.3
  dio: ^4.0.6
  decimal: ^2.3.0
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  flutter_html: ^2.2.1
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
